### ISSUE TITLE
Some mechanics feedback

### ISSUE THREAD

**Issue by nlzz22** [SanokeInc/Living-Space#29]
maybe change to 3 lives per level, if die go back previous level while keeping money earned

end stage, auto collect all coins
- Not sure if we want all these though, thats why I lump them together.

**Comment by tgqiang** [comment]
> > End stage - auto collect all coins sounds feasible. (loop through coins array, add all values to player, then remove all appearances of coins) ==> implemented in my branch currently
> > 
> > 3 lives per level + rollback to previous level & keep $$ earned upon death: also feasible, justifies NOT NERFING any of our stages (implementing this effectively closes issue #6) ==> #28 can also be closed

**Comment by tgqiang** [comment]
[CURRENT UPDATE] Both mechanics are implemented in my branch but code has not been pushed to the branch. If you all want to test these mechanics I can push the code to my branch then you all can test it out on my branch.

**Comment by tgqiang** [comment]
First point raised deemed not needed. Second point implemented.
