### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by tgqiang** [SanokeInc/Living-Space#4]
Sound effects needed for various game elements.

Possible list of elements requiring sound effects (subjected to variation):
1. Spaceship (Done)
a) <s>Fire Missile</s> Done
b) <s>Move</s> (I don't think really need... I think there's too much sound clutter in any 1 stage)
c) <s>Hit-by-alien</s> Done
d) <s>Crash</s> Done
e) <s>Upgrades</s> Done
1. Alien (Done)
   a) <s>Alien-speaking or something of the like</s> (I don't think really need... I think there's too much sound clutter in any 1 stage)
   b) <s>Shot by missile?</s> Done
   c) <s>Warning before Alien Spawn</s> Not needed
2. <s>Level completion</s> done by QX + Full game completion music/sound effects

**Comment by nlzz22** [comment]
Consider adding:
1. <s>Button Clicking sound (for the various menus / screens)</s> Done
2. <s>Coin collect sound</s> Done

**Comment by tgqiang** [comment]
All done. If music changes are required, new issue can be posted.
